name: deploy

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            examples
          sparse-checkout-cone-mode: false

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: examples/pnpm-lock.yaml

      - name: Build VuePress site
        working-directory: examples
        run: pnpm docs:build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: examples/docs/.vuepress/dist
